[package]
name = "galaxy_nbody"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2018"

[dependencies]
ggez = "0.6.0"
vulkano = "0.18"
vulkano-shaders = "0.18"
glsl-layout = "0.3.2"
rand = "0.7.3"
nalgebra = "0.32.3"
